### ISSUE TITLE
Header: Book Now button should display the book form

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Genesis-Dental#15]
![image](https://cloud.githubusercontent.com/assets/12888048/15167701/b8b02aa6-175d-11e6-9ea7-21c56fd35c5b.png)

![image](https://cloud.githubusercontent.com/assets/12888048/15167718/d4ae1d6c-175d-11e6-8b02-d1e91e35aa09.png)

**Comment by algericotitandigital** [comment]
Change Scope

**Comment by romatitan** [comment]
Update in scope.
![image](https://cloud.githubusercontent.com/assets/12888048/15239856/47679afc-1918-11e6-8ca7-26c6afaae2f3.png)
