### ISSUE TITLE
Homepage: There's an opacity/shadow below the page featured image.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Genesis-Dental#29]
![image](https://cloud.githubusercontent.com/assets/12888048/15168733/ba37a378-1766-11e6-94dd-f14e46bfa4e6.png)
![image](https://cloud.githubusercontent.com/assets/12888048/15168759/f511c262-1766-11e6-8ec7-0167294e5d73.png)

**Comment by algericotitandigital** [comment]
This is just an enhancement of the design just to make to image not obviously seen to be cut if the content is too long.

**Comment by romatitan** [comment]
Dev enhancement.
