### ISSUE TITLE
Book Form: Missing form. 992px - 1199px 

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Genesis-Dental#62]
![image](https://cloud.githubusercontent.com/assets/12888048/15174520/a4fb2268-1794-11e6-9dd5-c5387bdc3302.png)
![image](https://cloud.githubusercontent.com/assets/12888048/15174536/ae413d30-1794-11e6-97d1-da99872cc7f1.png)

**Comment by algericotitandigital** [comment]
please try to read the scope for the booking form

**Comment by romatitan** [comment]
Related issue #15 

**Previous scope.**
https://cloud.githubusercontent.com/assets/12888048/15167701/b8b02aa6-175d-11e6-9ea7-21c56fd35c5b.png

**Updated in scope.**
![image](https://cloud.githubusercontent.com/assets/12888048/15239950/dd23ac16-1918-11e6-83c1-b47533e6cd4d.png)
