### ISSUE TITLE
Footer: Responsive checking

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Genesis-Dental#64]
align in one line (480px - 991px)
![image](https://cloud.githubusercontent.com/assets/12888048/15174820/0888453a-1796-11e6-9a26-3a7250925f5a.png)

**Comment by algericotitandigital** [comment]
Try to see the assets so that you have guide for responsive designs.

**Comment by romatitan** [comment]
Enhancement for 768px -991px
